/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fac152fd-0c1d-4e63-ac03-bfca3af3f6fd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PTjfkBqmC",
    "aws_user_pools_web_client_id": "a75tad63vpug9hbkal9df3aqv",
    "oauth": {}
};


export default awsmobile;
